# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
rand_tensor=torch.rand([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_tensor_2=torch.rand([1, 7])
# Perform matrix multiplication 
matrix = torch.matmul(rand_tensor, rand_tensor_2.T)
matrix, rand_tensor, rand_tensor_2

(tensor([[2.2037],
         [2.4776],
         [2.3184],
         [2.1131],
         [2.3178],
         [2.9869],
         [3.1957]]),
 tensor([[0.7380, 0.8658, 0.7414, 0.7403, 0.0711, 0.6453, 0.2662],
         [0.9165, 0.0134, 0.8827, 0.9713, 0.3251, 0.2096, 0.9526],
         [0.9081, 0.3736, 0.2671, 0.6744, 0.4490, 0.6785, 0.7287],
         [0.4937, 0.9839, 0.1354, 0.2608, 0.3374, 0.4545, 0.8034],
         [0.4943, 0.5131, 0.5908, 0.2326, 0.3308, 0.5483, 0.8546],
         [0.3385, 0.7904, 0.1184, 0.9350, 0.7259, 0.9428, 0.7036],
         [0.1655, 0.1105, 0.9472, 0.5147, 0.8293, 0.7728, 0.8941]]),
 tensor([[0.0083, 0.5255, 0.7827, 0.5023, 0.9335, 0.7670, 0.8606]]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED=0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
man_ran_tensor_1=torch.rand(size=(7, 7))
man_ran_tensor_2=torch.rand(size=(1, 7))

# Matrix multiply tensors
man_ran_matrix=torch.matmul(man_ran_tensor_1, man_ran_tensor_2.T)
man_ran_matrix, man_ran_matrix.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
RANDOM_SEED_1=1234
torch.manual_seed(RANDOM_SEED_1)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available else "cpu"
print(device)

# Create two random tensors on GPU
tens_1=torch.rand(size=(2, 3)).to(device)
tens_2=torch.rand(size=(2, 3)).to(device)
tens_1, tens_2

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
mat_1=torch.matmul(tens_1, tens_2.T)
mat_1, mat_1.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
ma_1=torch.max(mat_1)
# Find min
mi_1=torch.min(mat_1)
ma_1, mi_1

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
ama_1=torch.argmax(mat_1)

# Find arg min
ami_1=torch.argmin(mat_1)
ama_1, ami_1

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [4]:
# Set seed
torch.manual_seed(7)

# Create random tensor
ran_1=torch.rand(1, 1, 1, 10)

# Remove single dimensions
ran_sq=ran_1.squeeze()

# Print out tensors and their shapes
ran_1, ran_1.shape, ran_sq, ran_sq.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))